version: '3'
services:
  fast-api:
    container_name: app
    build: .
#    command: gunicorn -b 0.0.0.0:8000 todosapp.wsgi:application
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:80"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GITHUB_API_KEY: ${GITHUB_API_KEY}
  redis:
    container_name: redis
    image: redis
